import type { DeepValueResult } from "./types";
import MethodBadges from "./method-badges";
import FairValueCards from "./fair-value-cards";
import RecapTable from "./recap-table";
import ReportBody from "./report-body";

type Labels = {
  recapTableTitle: string;
  recapCurrentPrice: string;
  bearLabel: string;
  baseLabel: string;
  bullLabel: string;
};

type Props = {
  ticker: string;
  companyName?: string;
  reportDate: string;
  reportTypeLabel: string;
  markdown: string;
  result: DeepValueResult;
  currentPrice?: number | null;
  mosPercent?: number;
  labels: Labels;
};

// Full "equity research PDF" report layout — masthead, method/sector badges,
// fair-value cards, the AI's Markdown body, the recap table, and a disclaimer
// footer. Used identically by the live streaming panel (once analysis
// completes) and the saved-analysis detail page, so both surfaces render the
// exact same report. The `.print-report` wrapper is the scoping class the
// print stylesheet (app/print.css) targets — everything inside it is what
// ends up in the "Download PDF" output; app chrome around it stays hidden.
export default function ReportShell({
  ticker,
  companyName,
  reportDate,
  reportTypeLabel,
  markdown,
  result,
  currentPrice,
  mosPercent = 0,
  labels,
}: Props) {
  return (
    <div className="print-report space-y-4">
      {/* Masthead — letterhead-style report header */}
      <div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-800/60 pb-4 print:border-slate-300">
        <div>
          <h1 className="font-display text-xl font-semibold text-slate-100 sm:text-2xl print:text-slate-900">
            {companyName ?? ticker}
          </h1>
          <p className="font-mono text-sm text-slate-500 print:text-slate-600">{ticker}</p>
        </div>
        <div className="text-right text-xs text-slate-500 print:text-slate-600">
          <p className="font-medium uppercase tracking-wide text-slate-400 print:text-slate-500">{reportTypeLabel}</p>
          <p>{reportDate}</p>
        </div>
      </div>

      <MethodBadges sector={result.sector} method={result.method} />

      <FairValueCards result={result} currentPrice={currentPrice} mosPercent={mosPercent} />

      <div className="card break-inside-avoid print:border print:border-slate-300 print:bg-white print:shadow-none">
        <ReportBody markdown={markdown} />
      </div>

      <RecapTable
        result={result}
        currentPrice={currentPrice}
        mosPercent={mosPercent}
        title={labels.recapTableTitle}
        currentPriceLabel={labels.recapCurrentPrice}
        bearLabel={labels.bearLabel}
        baseLabel={labels.baseLabel}
        bullLabel={labels.bullLabel}
      />

      <p className="border-t border-slate-800/60 pt-3 text-xs text-slate-500 print:border-slate-300 print:text-slate-600">
        ⚠️ This report was generated by AI and is for informational purposes only. It does not constitute financial advice.
      </p>
    </div>
  );
}
